#! /bin/sh

### BEGIN INIT INFO
# Provides:     elevator-server
# Short-Description:    elevator-server - Persistent key-value store
# Description:      elevator-server - Persistent key-value store
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=`which elevator`
ELEVATOR_CLI=`which elevator-cli`
CONFIG_FILE=/etc/elevator/elevator.conf
DAEMON_ARGS="--daemon -c $CONFIG_FILE"
NAME=elevator
DESC=elevator
PIDFILE=/var/run/elevator.pid
LOGFILE=/var/log/elevator/elevator.log

test -x $DAEMON || exit 0
test -x $DAEMONBOOTSTRAP || exit 0

set -e

case "$1" in
  start)
    echo -n "Starting $DESC: "
    touch $PIDFILE $LOGFILE
    chown elevator:elevator $PIDFILE $LOGFILE
    if $DAEMON $DAEMON_ARGS
    then
        echo "$NAME."
    else
        echo "failed"
    fi
    ;;
  stop)
    echo "Stopping $DESC"
    if [ ! -e "$PIDFILE" ]
    then
      echo "failed"
    else
      kill -9 `cat $PIDFILE`
      rm -f $PIDFILE
    fi
    ;;

  restart|force-reload)
    ${0} stop
    ${0} start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
